### ISSUE TITLE
Login Error, failed to retrieve Access Token : Login failed: %s', Exception('Unknown Login error: Login Failed Captcha Required

### ISSUE THREAD

**Issue by LivioB74** [rospogrigio/daikin_residential#104]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.daikin_residential.config_flow
Source: custom_components/daikin_residential/config_flow.py:78
Integration: Daikin Residential Controller (documentation, issues)
First occurred: 03:21:29 (1 occurrences)
Last logged: 03:21:29

Failed to retrieve Access Token: ('Login failed: %s', Exception('Unknown Login error: Login Failed Captcha Required'))

**Comment by rospogrigio** [comment]
Somebody already had this issue and it solved this way: #49 .
Next time make sure you use the Search feature before posting 😉 
Please close the issue if the above solution works for you, bye!
