### ISSUE TITLE
Invalid repository message 

### ISSUE THREAD

**Issue by syrusfem** [rospogrigio/daikin_residential#106]
Adding this link: "https://github.com/rospogrigio/daikin_residential/" to  Home Assistant repository add on fail with the message: "https://github.com/rospogrigio/daikin_residential is not a valid add-on repository" .

I tried using "https://github.com/rospogrigio/daikin_residential" with the same result.

Home Assistant Info:

Home Assistant 2022.11.1 
Supervisor 2022.10.2 
Operating System 9.3 
Frontend 20221102.1

**Comment by rospogrigio** [comment]
How are you trying to add it? Can you describe the steps you are taking?

**Comment by syrusfem** [comment]
Hi , i am trying to add the link in   Add On Repository of Home Assistant (in [attachment the image)
![error](https://user-images.githubusercontent.com/34411560/200375201-5ba8e561-2d1b-4df4-aaa1-a6101882fe86.png)

Manually copying the folder in Home Assistant works correctly but adding it to Add on Repository is useful to track updates .

**Comment by rospogrigio** [comment]
But are you adding it in HACS or where? Please be more specific.

**Comment by syrusfem** [comment]
Sorry, my bad I'll research how to install HACS .

Thanks!
