### ISSUE TITLE
Failed to retrieve Access Token: Login Failed Captcha Required

### ISSUE THREAD

**Issue by clitters** [rospogrigio/daikin_residential#108]
Hi,

i've tried to get the integration to work, but i receive the error:
Failed to retrieve Access Token: ('Login failed: %s', Exception('Unknown Login error: Login Failed Captcha Required'))

Does anybody here know what to do on that?

**Comment by rospogrigio** [comment]
Have you tried the search function? Like here: https://github.com/rospogrigio/daikin_residential/issues?q=is%3Aissue+captcha
Looks like you can find a solution in #49.
Looks like it's time to put this on a FAQ section in the README...

**Comment by clitters** [comment]
Thank you! It worked perfectly.
And sorry. I accidentially had the filter for open issues active. Thats why i didnt find it.
I am still wondering a little bit why that happened. I created a new account on my second phone with email authentication. With this account i was not able to log in on: https://my.daikin.eu/content/daikinid-cdc-saml/en/login.html
Now i've created a new account there and it worked like a charm.
Maybe i did something wrong before.
Anyways Thank you for the great integration and your support!
