### ISSUE TITLE
Communication failing

### ISSUE THREAD

**Issue by joydashy** [rospogrigio/daikin_residential#114]
Since a couple days HASS is no longer talking to my A/C:

> Logger: homeassistant.config_entries
> Source: custom_components/daikin_residential/daikin_api.py:119
> Integration: Daikin Residential Controller ([documentation](https://github.com/rospogrigio/daikin_residential/), [issues](https://github.com/rospogrigio/daikin_residential/issues))
> First occurred: January 13, 2023 at 9:34:00 AM (1 occurrences)
> Last logged: January 13, 2023 at 9:34:00 AM
> Error setting up entry Daikin for daikin_residential
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/daikin_residential/__init__.py", line 85, in async_setup_entry
>     devices = await daikin_api.getCloudDevices()
>   File "/config/custom_components/daikin_residential/daikin_api.py", line 488, in getCloudDevices
>     self.json_data = await self.getCloudDeviceDetails()
>   File "/config/custom_components/daikin_residential/daikin_api.py", line 484, in getCloudDeviceDetails
>     return await self.doBearerRequest("/v1/gateway-devices")
>   File "/config/custom_components/daikin_residential/daikin_api.py", line 117, in doBearerRequest
>     return await self.doBearerRequest(resourceUrl, options, True)
>   File "/config/custom_components/daikin_residential/daikin_api.py", line 119, in doBearerRequest
>     raise Exception("Communication failed! Status: " + str(res.status_code))
> Exception: Communication failed! Status: 503

Home Assistant 2023.1.4
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

**Comment by rospogrigio** [comment]
This is not an issue in the Integration, it's server-side. Sometimes they work on the servers and downtimes happen.
I had a couple of days of downtime too but everything is back to normal now.
Closing the issue,

**Comment by rospogrigio** [comment]
Maybe they add some parameter that allows them to filter which calls are coming from their app and which are external and they are able to filter them, or maybe it's just a matter of routing, I frankly don't know.

**Comment by joydashy** [comment]
Already down for a week now, really sucks! And I don't see anyone else complaining so I wonder why it's seemingly only hitting me.

**Comment by rospogrigio** [comment]
Maybe you can try to relogin/change password? Not sure it would help though, because 503 stands for "Service unavailable"...

**Comment by joydashy** [comment]
Ok this is very odd, I took the following steps:

- Change Daikin ID password through Onecta app
- Logout Onecta app and back in
- Remove Daikin configuration from HASS integration page --> fails to remove it
- Restarted HASS
- 
After this, the integration is back, and online, and the A/C works.

I don't understand this at all...
