### ISSUE TITLE
Failed to retrieve Access Token: Login failed

### ISSUE THREAD

**Issue by Maacklm** [rospogrigio/daikin_residential#119]
Trying to add integration, I entered the login and password but doesn't work log show : "Failed to retrieve Access Token: ('Login failed: %s', Exception('Unknown Login error: Login Failed Captcha Required'))"

**Comment by rospogrigio** [comment]
Known problem. Try searching in other issues, or read the "Known Issues and troubleshooting" section in the Readme...
