### ISSUE TITLE
New firmware 1.23.0 revision by Daikin for BRP069C4.... >   (BRP069B4... is also changed)

### ISSUE THREAD

**Issue by ALAMILLA1** [rospogrigio/daikin_residential#122]
From yesterday 24/02/2023, opening the Daikin APP ONECTA  proposes update of APP and update to the firmware of the BRP069C4.... adapter access point broadcast.

¿Does anyone know if this new firmware is compatible with the smooth operation of the rospogrigio  / daikin_residential with Home Assistant at the current revision?

**Comment by cypherbits** [comment]
Same here, the new firmware version fixes the security issue of the DaikinAP wifi always enabled. But I still haven't updated it because I'm afraid of breaking this integration.

**Comment by mihsu81** [comment]
Tested on my 2 ACs. Working fine and the APs are gone.
![Screenshot_2023-02-25-15-56-11-64_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/40715497/221363840-ef154754-4db1-458d-8870-1a0e688696a7.jpg)

**Comment by cypherbits** [comment]
Just updated and everything is working fine. Nice.

**Comment by ok11** [comment]
after FW update all five units run flawlessly
