### ISSUE TITLE
Doesn't work with Japan models

### ISSUE THREAD

**Issue by AndyDiags** [rospogrigio/daikin_residential#13]
I just tested this out on my Japan model Daikin, and username/pass login is failing.

I ran Charles on from my iPhone using the Japan issued iPhone app, and the endpoints seem different.  The sequence also is a bit different and easier.  I think in Japan, Daikin build their own solution, while for rest of world they are using AWS.

Would you be able to see if you could extend your library to work with Japan distributed Daikin A/C units as well?  In Japan, they updated the firmware on all order Wi-Fi adaptors to use Cloud based solutions :(

I can provide the full Charles log.  Attached screenshot should give a good idea of what's going on.

My Register URL:
https://api.daikinsmartdb.jp/premise/dsiot/login

Request
```
{
	"code": "[cert]",
	"client_id": "[unique id]",
	"uuid": "[uuid]",
	"client_secret": "[value]",
	"grant_type": "authorization_code"
}
```
Response:
```
{
	"rsc": 2000,
	"uid": "0160592",
	"access_token": "[token]",
	"id_token": "[token]",
	"expires_in": 3600,
	"refresh_token": "[token]"
}
```
<img width="1954" alt="1st call" src="https://user-images.githubusercontent.com/85074233/133485441-186a4813-02f7-4d22-9e26-84db18ff9114.png">

<img width="1954" alt="2nd call" src="https://user-images.githubusercontent.com/85074233/133485447-43d3aea1-2839-4dca-8847-f233cd3813af.png">

**Comment by rospogrigio** [comment]
Ok but first of all could you just try to change the endpoints used in my code with the ones you sniffed and see if it works? Then you could submit a PR and I can work out on a way to have this part configurable.

**Comment by AndyDiags** [comment]
Just changing the endpoint doesn't work
I'm not sure if I have the endpoints correct, but I get the following error when I do change them:
`2021-09-16 21:31:56 ERROR (MainThread) [custom_components.daikin_residential.config_flow] Failed to retrieve Access Token: ('Login failed: %s', Exception('Unknown Login error: invalid loginID or password'))`

The two endpoints are:
https://api.daikinsmartdb.jp/premise/dsiot/login
https://api.daikinsmartdb.jp/premise/dsiot/token

So I think these should be correct...
DAIKIN_CLOUD_URL = "https://api.daikinsmartdb.jp"
DAIKIN_ISSUER = "https://api.daikinsmartdb.jp"
            
"authorization_endpoint": DAIKIN_CLOUD_URL + "/premise/dsiot/login",
"token_endpoint": DAIKIN_CLOUD_URL + "/premise/dsiot/token",

**Comment by rospogrigio** [comment]
What you did looks correct but probably there is something else to do, there are several requests that take place to retrieve the token. If you want I can send you just the script that retrieves the tokenset and you can play with that until you find the correct procedure, it would be comfortable because you don't need to restart HA every time you want to try.
Let me know...

**Comment by AndyDiags** [comment]
Yes that would be helpful.  Thank you.

In my case, the token is returned on the very first API request, `/login`.  And the one thing that I'm not clear is that in the request body, there's a value called `code`.  This seems to be some sort of base64 encoded hash of username+password, perhaps mixed with a private key only known by app as well as the current time as the value is unique on every login.  This leads me to believe that we can not replicate this API due to not being able to generate value for `code`.

The good thing is that I can use the app to generate the token only once, copy the token manually, and then have the script use that token and automatically renew the token whenever it expires as renewal does not require any credentials.

**Comment by rospogrigio** [comment]
OK you find the tokensaver.py script now in the tools folder. It contains more or less the same code used in the integration, you'll have to edit it until you get a successful token retrieval. When it does, it will show you a summary of your daikin units. It has to be launched with 2 parameters (email and password, of course). When you have a working script, send it to me and I'll try to include it in the integration.
Good luck...

**Comment by AndyDiags** [comment]
Just an overdue follow up on this.  The API's used on a Daikin sold in Japan is pretty much completely different and everything would need to be rewritten from scratch.  It's based on most of the same principles, but the API's are different.  If someone would like to incorporate this for Japan issued Daikin air conditioners, you'd be better off starting a separate project.  It's seems possible, but it's not a straight forward port.

**Comment by rospogrigio** [comment]
If only the token retrieval part is different I think we can integrate it, but if also the JSON structure differs then I agree with you that it's better to keep things separated.
Thank you for your follow up, bye!

**Comment by AndyDiags** [comment]
> If only the token retrieval part is different I think we can integrate it, but if also the JSON structure differs then I agree with you that it's better to keep things separated.
> 
> Thank you for your follow up, bye!

JSON structures are different :(
