### ISSUE TITLE
What the IoT class of this integration?

### ISSUE THREAD

**Issue by e-gaulue** [rospogrigio/daikin_residential#131]
According to the README.md, we could suppose it to be "cloud polling" (https://www.home-assistant.io/blog/2016/02/12/classifying-the-internet-of-things/#classifiers).

Or is the cloud just used to get the devices "key" and then it's "local polling"? 

Could it be clearly mentioned in README.md?

**Comment by rospogrigio** [comment]
It really is cloud polling, there is no known way to have local connection to the units (actually some http data can be received but there seems to be no way to send commands or get relevant data).
OK maybe I can specify this in the readme in the future, thanks.
