### ISSUE TITLE
New Firmware 1.24.0 compatibility?

### ISSUE THREAD

**Issue by jmtatsch** [rospogrigio/daikin_residential#135]
Does anybody know whether we can safely update to firmware 1.24.0 and use this HA integration?

**Comment by Ringo982** [comment]
Hi
I updated to 1.24 and all my devices became unavailable..
I'm running HA 2023.5.3
Help

**Comment by asic79** [comment]
Just updated to firmware 1.24 and the integration seems to be working no problem.
Home Assistant 2023.5.3
Supervisor 2023.04.1
Operating System 10.1

**Comment by rospogrigio** [comment]
It is good practice to close the issues when they are solved, thank you
