### ISSUE TITLE
Firmware revision not updated in the device info

### ISSUE THREAD

**Issue by jwillemsen** [rospogrigio/daikin_residential#136]
I upgraded to 1.24.0 but in home assistant I will see 1.23.0 in the device info. After a reboot of HA the correct firmware revision is shown, but that is just a workaround

**Comment by weaselchops** [comment]
I just did a reload of the integration. Worked for me.

**Comment by jwillemsen** [comment]
Yes, reload will also work, but shouldn't be required

**Comment by jwillemsen** [comment]
Closing, https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.0.0 shows the firmware revision not cached
