### ISSUE TITLE
Request documentation Onecta calls

### ISSUE THREAD

**Issue by adr001db** [rospogrigio/daikin_residential#138]
Hallo Rospogrigio,
Great work! Iam trying to translate this Integration to a Java plugin for Openhab3.
My problem is that iam not that great with Python and HomeAssistant. ;o)

It would help me a lot to get some documentation how calls to Daikin Onecta look like.

Can you help me with this ?

thanks in advance.

**Comment by rospogrigio** [comment]
There is no documentation but they are just HTTP calls sending and retrieving JSON structures, that you can easily derive by reading the code.
Sorry for not being more helpful but I'm too busy at work this period.
Good luck!
