### ISSUE TITLE
Daikin not connected with ha to the beta   2023.6.0b4

### ISSUE THREAD

**Issue by homeyjoenka** [rospogrigio/daikin_residential#143]
Daikin intergratie its not working with beta can you thit fix it?
[
![IMG_0516](https://github.com/rospogrigio/daikin_residential/assets/61145850/96143cf2-20dd-4740-86e3-bc481e2aa029)
![IMG_0515](https://github.com/rospogrigio/daikin_residential/assets/61145850/d661a21c-88c2-4a88-acf8-2b9d6d47f471)
](url)

**Comment by jwillemsen** [comment]
Did you install the latest release of the integration?

**Comment by homeyjoenka** [comment]
When is the latest release? What’s the url?

**Comment by homeyjoenka** [comment]
We have this 
![IMG_0520](https://github.com/rospogrigio/daikin_residential/assets/61145850/f8cffb54-9217-4421-9e46-5cb5723858b2)

**Comment by jwillemsen** [comment]
That is the latest, please attach the ha logs and device diagnostics

**Comment by homeyjoenka** [comment]
Hi you can close this issue it’s work now we have not the latest release

**Comment by homeyjoenka** [comment]
Thank you for fast reaction I am happy now thank you so much for all this work for this intergration

**Comment by jwillemsen** [comment]
Please close this issue, I can’t
