### ISSUE TITLE
Data not updated

### ISSUE THREAD

**Issue by jdserras** [rospogrigio/daikin_residential#159]
Very often the data is not updated from cloud, namely temperatures.

**Comment by DanielHons** [comment]
I am having the same issue since two days, but not only in HA but also with the official ONECTA-App.

**Comment by rospogrigio** [comment]
Then maybe it's not an issue of the integration but of Daikin itself?? The Integration just shows the data it receives from the cloud, it just can't stop working.

**Comment by DanielHons** [comment]
Aggreed, I opened a ticket to the German support but I would also recommend others, who face this issue, to get in contact with them.

**Comment by DanielHons** [comment]
@jdserras I found the error on my side in a blocked DNS query. The Device was simply not able to find the server to sent it's updates to.
