### ISSUE TITLE
[Issue] Airco Weekly Heat Energy Consumption

### ISSUE THREAD

**Issue by smoldersonline** [rospogrigio/daikin_residential#175]
Thank you very much for sharing this integration!

_Edit: brainless question, sorry!_

In addition (and related), ONECTA app also reports 'Total (energy consumption) this month'. Would it be possible t include this in the integration?

Thank you!

**Comment by OcinO88** [comment]
If you go to the onecta app and select total for this month, it only shows yearly, weeky and daily values, just like you get in HA. The montly is not something that's recorded with the airco's, it's most probably a calculation of all days of the month. You could create a sensor in HA, that does the same, it should be added to your configuration.yaml file. I have one that adds up all 3 of my airco units, that looks like this: (maybe this can help you create your own. If you create a trigger, you can update it once a day, say at 23:59):
  - sensor:
       # Keep track of how much energy has been consumed by all airco's - weekly
      - name: "Airco weekly heating total energy consumed"
        unique_id: "Airco weekly heating total energy consumed"
        icon: 'mdi:fire'
        state: '{{ states("sensor.livingroom_weekly_heat_energy_consumption") |float(0) + states("sensor.bedroom1_weekly_heat_energy_consumption") | float(0) + states("sensor.bedroom2_weekly_heat_energy_consumption") | float(0) }}'
        unit_of_measurement: "kWh"

Another option, would be to go to settings / dashboards / energy, and then add their daily usage to the "individual devices" section. Note that it can take about an hour for data to show up. When you select "month" on top, it'll show the monthly consumption for that device.

**Comment by smoldersonline** [comment]
Thanks! That makes sense.

Your option #2 works just fine!

**Comment by jwillemsen** [comment]
Great, can you close this issue?
