### ISSUE TITLE
Invalid config for [daikin_residential]: expected str for dictionary value @ data['daikin_residential']['email']. Got ['XXXXXXX@gmail.com'] expected str for dictionary value @ data['daikin_residential']['password']. Got ['XXXXXXX']. 

### ISSUE THREAD

**Issue by pcorres** [rospogrigio/daikin_residential#181]
Hello, This is a great plugin.. THANK YOU
Everything worked well with my username and password. Since today I get the error message mentioned above. I did not change anything.
However I did try to move Home Assistant to another machine, with the result that the plugin does not work neither on the old nor new machine.
These are lines in the config file:

daikin_residential:
  email: [XXXXXXX@gmail.com]
  password: [XXXXXXX]

Thanks in advance
Peter

**Comment by jwillemsen** [comment]
See https://github.com/rospogrigio/daikin_residential/pull/177/files, instructions are not correct

**Comment by pcorres** [comment]
you made my day! Thank you for the super  fast reply. Issue solved. Peter
