### ISSUE TITLE
Control fan from automation?

### ISSUE THREAD

**Issue by svenove** [rospogrigio/daikin_residential#188]
I want to control the fan speed from an automation, but I can’t figure out how to do it. In the Daikin device, there is no fan control…?

**Comment by svenove** [comment]
Solved:
![image](https://github.com/rospogrigio/daikin_residential/assets/4579212/fb2a489d-fbd2-4f25-b8a6-14dd489c4967)

**Comment by jwillemsen** [comment]
Can you attach the automation as text, easier for others

**Comment by svenove** [comment]
Sure:
```action:
  - service: climate.set_fan_mode
    target:
      device_id: xxxxxxxxxxxxx
    data:
      fan_mode: "5"
