### ISSUE TITLE
daikin perfera firmware changelog

### ISSUE THREAD

**Issue by Rvh91** [rospogrigio/daikin_residential#191]
Hi all,

Sorry to do this here, as it is not really an issue with the integration, I just have no idea who to reach out to otherwise. My ONECTA app tells me I can upgrade the firmware for my perfera units from 1.24.0 to 1.28.0. This seems nice and all, but I cant seem to find a changelog anywhere (even contacting customer support yields nothing. Basically they tell me to contact the installer instead as they dont deal with end customers directly). 

Seeing as I'm relying on HA to operate these units I want to make sure that functionality isn't broken once firmware is upgraded. Does anyone know what has changed between these two firmware versions? and more importantly, can anyone verify that this HA integration still works on 1.28.0?

Thanks!

**Comment by jmtatsch** [comment]
1.28.0 works fine for me.
Changes probably have been mostly about getting their wifi controllers stable.

**Comment by rgerhards** [comment]
works for me as well.

**Comment by Rvh91** [comment]
thanks!
