### ISSUE TITLE
[Issue]: min/max values for temperature demand 

### ISSUE THREAD

**Issue by gismo2004** [rospogrigio/daikin_residential#193]
I am using two times the same device, but for some reason the min and max values for temperature demand is different. Can this be set somewhere I am not aware of?

![Screenshot_20231224-073030.png](https://github.com/rospogrigio/daikin_residential/assets/2325636/93fd1e6c-4922-4395-97d4-621f71b3371b)

**Comment by jwillemsen** [comment]
Min/max are read from the daikin data, see the device diagnostics for the json

**Comment by gismo2004** [comment]
Ohh, now that I have checked onecta app I see the same thing. Very interesting, since I have 2x the "same" device.

Do you know a way to set this somehow?

**Comment by jwillemsen** [comment]
Please attach the device diagnostics, could be due to some mode setting

**Comment by gismo2004** [comment]
It is a mode setting! Thanks for pointing me to this direction.

![Screenshot_20231224-120327.png](https://github.com/rospogrigio/daikin_residential/assets/2325636/6a5fa505-c09b-4463-b212-97d982aad718)
