### ISSUE TITLE
[Issue]: Startup fails on some entities

### ISSUE THREAD

**Issue by ridderr** [rospogrigio/daikin_residential#194]
My Control, to switch the Daikin, is greyed out. The sensors are still working.
See in attached log the errors which are reported.

![Schermafbeelding 2023-12-29 110724](https://github.com/rospogrigio/daikin_residential/assets/12719238/f4ffa51b-f124-4aad-b5e9-c0c81d28b7d9)

[home-assistant_daikin_residential_2023-12-29T09-55-01.951Z.log](https://github.com/rospogrigio/daikin_residential/files/13792519/home-assistant_daikin_residential_2023-12-29T09-55-01.951Z.log)

**Comment by ridderr** [comment]
Additional logging:
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:507
Integration: Climate (documentation, issues)
First occurred: 10:54:25 (2 occurrences)
Last logged: 10:54:26

Error adding entities for domain climate with platform daikin_residential
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 333, in capability_attributes
    if ClimateEntityFeature.TARGET_HUMIDITY in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

**Comment by ridderr** [comment]
Latest version:
Core
2024.1.0b1
Supervisor
2023.12.1
Operating System
11.3.rc1
Frontend
20231228.0

**Comment by jwillemsen** [comment]
Ok, I think something did change in the core which breaks the integration

**Comment by jwillemsen** [comment]
Maybe try https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.2.12

**Comment by jwillemsen** [comment]
Please upgrade to beta 2

**Comment by ridderr** [comment]
Hi, I had to change from [rospogrigio](https://github.com/rospogrigio) to this version. All seems to work again. Top job!!
And as a bonus, I now have far more options :-)

**Comment by jwillemsen** [comment]
Great, please close this issue
