### ISSUE TITLE
[Feature] Add an entity that show if the unit is online/offline

### ISSUE THREAD

**Issue by svenove** [rospogrigio/daikin_residential#197]
I would like to send a push notification if the unit is offline/unavailable for 30 mins. Could there be an entity that simply shows if the device is online or not?

**Comment by jwillemsen** [comment]
I think you can use the `available` property (https://developers.home-assistant.io/docs/core/entity/#generic-properties), this is read from the `isCloudConnectionUp` value as returned by Daikin

**Comment by svenove** [comment]
@jwillemsen sounds great! But how do I access that property from an automation? Thought I would find it as an attribute on the entity, but I can’t find it there.

**Comment by jwillemsen** [comment]
Maybe https://community.home-assistant.io/t/is-it-possible-to-trigger-an-automation-if-an-entity-goes-missing/417312/11 helps, google is your friend ;-)

**Comment by svenove** [comment]
@jwillemsen is it the state of the device that changes to “unavailable”? Been using HASS for 1,5 month and still struggle a bit to grasp device/entity and state/attribute/property. 

Might be I can use this from the forum link you provided: https://github.com/jazzyisj/unavailable-entities-sensor

**Comment by svenove** [comment]
@jwillemsen  oh, I found it! On my phone I didn’t notice the list of states was “scrollable”… 🤦🏼‍♂️😂

Thanks!

![IMG_5072](https://github.com/rospogrigio/daikin_residential/assets/4579212/b47a4f1c-33c2-4796-bda6-6dcb1b8824c0)
