### ISSUE TITLE
Failed to unload

### ISSUE THREAD

**Issue by parabag** [rospogrigio/daikin_residential#199]
Hello,
I got this strange error message in the Integration page "failed to unload":
![image](https://github.com/rospogrigio/daikin_residential/assets/48617367/18699875-3043-44da-8844-8fefd32c86e8)

Can you please advise?

thanks

Luca P.

**Comment by jwillemsen** [comment]
I think it is a bug, try to restart HA

**Comment by parabag** [comment]
did it many times... but the message always come back...

**Comment by jwillemsen** [comment]
Try to fix your `async_unload_entry` locally with this version https://github.com/jwillemsen/daikin_residential_altherma/blob/4cd2b82f7df40839843a96a8694b2eeaf4b8e508/custom_components/daikin_residential_altherma/__init__.py#L94
