### ISSUE TITLE
[Issue]: Failed to retrieve Access Token: ('Error trying to extract API version: %s', TypeError('get() takes 1 positional argument but 2 were given'))

### ISSUE THREAD

**Issue by seikra** [rospogrigio/daikin_residential#202]
Icant get log from this, but this happens when trying to log in.

"Tämä virhe on peräisin mukautetusta integroinnista.

Logger: custom_components.daikin_residential.config_flow
Source: custom_components/daikin_residential/config_flow.py:58
Integration: Daikin Residential Controller (documentation, issues)
First occurred: 03.13.00 (7 occurrences)
Last logged: 04.24.03

Failed to retrieve Access Token: ('Error trying to extract API version: %s', TypeError('get() takes 1 positional argument but 2 were given'))
"

**Comment by seikra** [comment]
Thanks! Problem was with toshiba ac integration. I deinstalled it and wola!

**Comment by jwillemsen** [comment]
Ok, btw, https://github.com/jwillemsen/daikin_residential_altherma provides more sensors and control for your AC units
