### ISSUE TITLE
[Issue]: No devices or entities

### ISSUE THREAD

**Issue by vivanec** [rospogrigio/daikin_residential#207]
Hi,
I've added this integration to my ha.
In the integration entries I have Daikin but it says no devices or entities.
When I download diagnostic I can see my daikin heating adapter with all values I need. From FW version, IP address, target temperature, current indoor temp, outdoor temp etc. It says that target temperature is settable.  
Only thing that is strange is datetime which has wrong value ("2021-12-24T03:42:00")
How can I add this to my HA?
Thanks

[daikin_debug.json](https://github.com/rospogrigio/daikin_residential/files/14375722/daikin_debug.json)

![daikin_debug_pic](https://github.com/rospogrigio/daikin_residential/assets/20595990/9dbddf32-a6ff-4b96-8c7f-88f441ed90a1)

**Comment by jwillemsen** [comment]
You have an Altherma device, this integration is for AC units only, see https://github.com/jwillemsen/daikin_onecta for an integration which supports both. The last stable release uses the 'old' Onecta API which will be deprecated March 11th 2024, the master branch is for the new OAuth2 Cloud API.

**Comment by vivanec** [comment]
Managed to create cloud api auth and it seems it works.
Thank you!

**Comment by vivanec** [comment]
Managed to create OAuth2 app login and it seems to work.
Thank you!
