### ISSUE TITLE
[Issue]: all devices offline, no login possible anymore.

### ISSUE THREAD

**Issue by michelkorthout** [rospogrigio/daikin_residential#209]
Running:
Core 2024.3.0
Supervisor 2024.02.1
Operating System 12.0
Frontend 20240306.0

The logfiles shows an issue with the token:

Traceback (most recent call last):
  File "/config/custom_components/daikin_residential/daikin_api.py", line 393, in retrieveAccessToken
    raise Exception("Unknown Login error: " + response["errorDetails"])
Exception: Unknown Login error: Missing required fields for registration: data.profile.communicationLanguage, data.profile.countryResidence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/daikin_residential/daikin_api.py", line 177, in refreshAccessToken
    await self.retrieveAccessToken(data[CONF_EMAIL], data[CONF_PASSWORD])
  File "/config/custom_components/daikin_residential/daikin_api.py", line 395, in retrieveAccessToken
    raise Exception("Login failed: %s", e)
Exception: ('Login failed: %s', Exception('Unknown Login error: Missing required fields for registration: data.profile.communicationLanguage, data.profile.countryResidence'))

**Comment by jwillemsen** [comment]
This integration is end of life, see readme, migrate to https://github.com/jwillemsen/daikin_onecta

**Comment by michelkorthout** [comment]
Thanks! Just installed the new one! all is fine now

**Comment by jwillemsen** [comment]
Great, can you close this issue?
