### ISSUE TITLE
Failed to retrieve access token set.

### ISSUE THREAD

**Issue by Croovy1988** [rospogrigio/daikin_residential#210]
The Daikin Residential Controller didn't work anymore. Nothing happens. No Update, no reboot. I tried to get a new token, but there Codes the error:
Failed to retrieve access token set.

**Comment by jwillemsen** [comment]
Daikin changed their cloud support, see https://github.com/jwillemsen/daikin_onecta as replacement

**Comment by Croovy1988** [comment]
Thanks a lot. My problem is solved. Thank you very much and have a nice day.
