### ISSUE TITLE
Show Energy consume in energy panel

### ISSUE THREAD

**Issue by lours1** [rospogrigio/daikin_residential#30]
Hello,

I try to integrate my daikin like my mitshubisi in the energy panel but the sensor are not listed.
And there is a ling to this article, if i want to see it [link to doc]( https://www.home-assistant.io/more-info/statistics/)

Is it possible to improve your integration to be able to access data in energy panel?

thank you

**Comment by rospogrigio** [comment]
It is possible for sure but I have absolutely no time to work on this right now and for the next months I'm afraid, so if anyone can propose a PR I'd be happy to merge it.
Sorry, thank you for the suggestion

**Comment by lours1** [comment]
i'm also developer, but not python.
But it's seem to be a good challenge, i'll try to implement and provide you a change request

**Comment by lours1** [comment]
Hello i made the change, you can check it here https://github.com/rospogrigio/daikin_residential/pull/32

**Comment by henrikrox** [comment]
@lours1 is this fixed? seems the PR was deleted, and not merged?

**Comment by rospogrigio** [comment]
Yeah it was deleted after a merge, and now it is replaced by #35. I don't have time to test it now but I hope in the next week to be able to do it.

**Comment by TASSDevon** [comment]
@rospogrigio Happy NY! Do you have any idea when you will have time to test this? No rush, just wondering. Thanks for all your efforts!

**Comment by Neo2SHYAlien** [comment]
@TASSDevon actually in PR #42 have working code ;) You can use https://github.com/rospogrigio/daikin_residential/tree/lts_sensors branch instead of master

**Comment by jwillemsen** [comment]
This should work now, can you retest?
