### ISSUE TITLE
Set the temperature of the device

### ISSUE THREAD

**Issue by OcinO88** [rospogrigio/daikin_residential#37]
Will it be a future option to set the temperature of the device? Right now it is only possible to set the hvac mode (heat / cool / etc). I would like to be able to create an automation that will set the cooling config, based on the outside temperature (i.e. when it is 27 degrees outside, to automatically set the cooling temperature to 24; so to set the cooling temperature x degrees lower than the outside temperature). This way it won't be too cold inside and the difference between inside and outside won't be too big.

**Comment by rospogrigio** [comment]
What do you mean? You should be able to set the temperature without any problem (the service is climate.set_temperature)...

**Comment by OcinO88** [comment]
Ah! Great, I did not know that... I used the "device" option to change hvac setting (and there is no such setting), but indeed, if I change that to call service, then there is the option to do so!
