### ISSUE TITLE
Device filtered out

### ISSUE THREAD

**Issue by qazqazie** [rospogrigio/daikin_residential#46]
Hello, 

I get the errors message below. The device that is filtered out is the device I want to connect which is an Alterma unit. See pictures for specs. 

Logger: custom_components.daikin_residential.daikin_api
Source: custom_components/daikin_residential/daikin_api.py:493
Integration: Daikin Residential Controller (documentation, issues)
First occurred: 13:34:24 (1 occurrences)
Last logged: 13:34:24

Device with ID '036e46f4-3139-4dc3-94da-3ed51a640f86' is filtered out

Many thanks
Brian
![Screenshot_2021-12-23-14-48-44-316_com daikineurope online controller](https://user-images.githubusercontent.com/76488780/147249690-251ef7b8-3d17-47a5-a31e-4149c438c5d0.jpg)

**Comment by rospogrigio** [comment]
Oh, I see. You have a heat pump, which is currently not supported by this integration, which only applies to air conditioners.
I know that @speleolontra has been working on adapting my integration for heat pumps, maybe he can give you some support and provide you the integration he's been working on.
See also #36.
Bye...

**Comment by qazqazie** [comment]
Many thanks
