### ISSUE TITLE
Energy meter are unavailble.

### ISSUE THREAD

**Issue by xisio78** [rospogrigio/daikin_residential#47]
With version core-2021.12.6  /supervisor-2021.12.2 energy meter are unavailble.
Few days ago was fine.

![image](https://user-images.githubusercontent.com/63660194/147699307-a3266544-a3ee-4ee3-853d-ed76d178776a.png)

**Comment by xisio78** [comment]
![image](https://user-images.githubusercontent.com/63660194/147703832-9d502a27-be3e-4e06-9d6c-0d0d7b976bad.png)

**Comment by henrikrox** [comment]
Same problem @rospogrigio  Tried 2012.12.7 also same problem. tried readding the integration, now only I get inside temperature
![Screenshot 2021-12-30 at 10 58 59](https://user-images.githubusercontent.com/6884716/147741395-fa3f646d-fbcd-49f0-8193-3a06b70a5baf.png)

**Comment by xisio78** [comment]
Now is ok... I don't know what happened..


![image](https://user-images.githubusercontent.com/63660194/147782052-ad1341ae-34b3-4055-8c65-2fa9ae4bcda5.png)

**Comment by henrikrox** [comment]
Also ok here, maybe a glitch with daikin cloud
