### ISSUE TITLE
Python 3.10.2

### ISSUE THREAD

**Issue by stefanolanfranco** [rospogrigio/daikin_residential#63]
Hi, i've installed Python 3.10.2 and now the integration don't work. I tried to workaroud with no success.
I post the error log. I can't obtain the diagnostics now since doesn't load the integration.

Logger: homeassistant.setup
Source: setup.py:162
First occurred: 00:32:03 (1 occurrences)
Last logged: 00:32:03

Setup failed for custom integration daikin_residential: Unable to import component: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by rospogrigio** [comment]
Looks like it's a problem of python 3.10, you can find a lot of people reporting this. Check this out for example: https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections
This integration is not using the collections library in any way.

**Comment by emanuelst** [comment]
Hi, I experienced the same issue. 

I tried updating oic to 1.4.0 and it fixed the issue for me. I also tried to create a pull request (my first one) to update oic to 1.4.0, would be really cool if this could be merged? 

Thanks for the awesome integration!

**Comment by EvertJob** [comment]
> Hi, I experienced the same issue.
> 
> I tried updating oic to 1.4.0 and it fixed the issue for me. I also tried to create a pull request (my first one) to update oic to 1.4.0, would be really cool if this could be merged?
> 
> Thanks for the awesome integration!
> 
> Edit: I think I made a mistake creating the pull request, it should now have been created correctly.

With what command did you fix this?

**Comment by emanuelst** [comment]
> > Hi, I experienced the same issue.
> > I tried updating oic to 1.4.0 and it fixed the issue for me. I also tried to create a pull request (my first one) to update oic to 1.4.0, would be really cool if this could be merged?
> > Thanks for the awesome integration!
> > Edit: I think I made a mistake creating the pull request, it should now have been created correctly.
> 
> With what command did you fix this?

I changed the version in the manifest.json file. 
The newest release also includes the change, so just using the newest version of the integration should work.
