### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by kazikskrz** [rospogrigio/daikin_residential#69]
Would you please advise why my integration stopped working?

Logger: custom_components.daikin_residential.daikin_api
Source: custom_components/daikin_residential/daikin_api.py:101
Integration: Daikin Residential Controller (documentation, issues)
First occurred: 17 maja 2022, 07:38:35 (1 occurrences)
Last logged: 17 maja 2022, 07:38:35

REQUEST FAILED: HTTPSConnectionPool(host='api.prod.unicloud.edc.dknadmin.be', port=443): Max retries exceeded with url: /v1/gateway-devices (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4c86e1b130>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by Neo2SHYAlien** [comment]
Did you try your connectivity to api.prod.unicloud.edc.dknadmin.be ? For example 
`curl -I https://api.prod.unicloud.edc.dknadmin.be`

**Comment by kazikskrz** [comment]
I get the following error when opening 1st link in chrome

`403 ERROR
The request could not be satisfied.
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: opzO4Tsxb6UWeiyvTANo7bS-3C5Q2aOuJlxFOuXZvO82vmROJveD_g==`

and this with second link

`{"message":"Missing Authentication Token"}`

**Comment by kazikskrz** [comment]
it turns that in Configuration.yaml I had defaulted email: and  password.
I entered my cridentials and restarted HA and it works back again.
Thank you for this great integration.
