### ISSUE TITLE
Add support for demandControl

### ISSUE THREAD

**Issue by jwillemsen** [rospogrigio/daikin_residential#71]
The BRP069C4x 1.12.84 firmware adds support for `demandControl`. Below the json, in the onecta app I can first select on/off, when set on I can select automatic, manual with a percentage between 40 and 100 and use a schedule.

```
            "demandControl": {
              "ref": "#demandControl",
              "settable": true,
              "value": {
                "currentMode": {
                  "value": "auto",
                  "settable": true,
                  "values": [
                    "off",
                    "auto",
                    "fixed",
                    "scheduled"
                  ]
                },
                "modes": {
                  "fixed": {
                    "stepValue": 5,
                    "value": 100,
                    "minValue": 40,
                    "maxValue": 100,
                    "settable": true
                  },
                  "scheduled": {
                    "settable": true,
                    "meta": {
                      "minIntervalBetweenActions": "00:01:00",
                      "maxActionsPerActionPeriod": 4,
                      "consecutiveActionsAllowed": true,
                      "actionPeriods": [
                        "monday",
                        "tuesday",
                        "wednesday",
                        "thursday",
                        "friday",
                        "saturday",
                        "sunday"
                      ],
                      "actionTypes": {
                        "currentMode": {
                          "settable": true,
                          "values": [
                            "off",
                            "fixed"
                          ]
                        },
                        "modes": {
                          "fixed": {
                            "stepValue": 5,
                            "minValue": 40,
                            "maxValue": 100,
                            "settable": true
                          }
                        }
                      }
                    },
                    "value": {
                      "actions": {}
                    }
                  }
                }
              }
            },
```

[config_entry-daikin_residential-c62f0b2c77dfabefa0e7ce2811aaf312.json.txt](https://github.com/rospogrigio/daikin_residential/files/8812137/config_entry-daikin_residential-c62f0b2c77dfabefa0e7ce2811aaf312.json.txt)

**Comment by joydashy** [comment]
This would be a great feature to add, as it is a typical setting which you would like to automate using Home Assistant. It could be used to balance the power usage based on solar panels for example.

**Comment by rospogrigio** [comment]
Mmm but I don't understand what it does, can anybody explain please?

**Comment by joydashy** [comment]
> Mmm but I don't understand what it does, can anybody explain please?

See:
https://ibb.co/RvQNdGg

**Comment by wiad** [comment]
Using this is also a way to trick the fan to run at an even speed instead of changing speed depending on the indoor temp (which can be annoying). You do this by decreasing the outdoor unit capacity and increasing the temp to a higher value than you would normally like. I for example set temp to 23c and then I use the demandcontrol function to control the actual temp - if it's too cold I increase the capacity and if its too warm I decrease it. 
If this setting was available in HA I could automate this which would be nice.

**Comment by lkaino** [comment]
I implemented the demand control on my fork: https://github.com/lkaino/daikin_residential/tree/demand_control_based_on_humidity

You control it by setting the humidity in Home Assistant.

It's based on v2.2.2 as I forgot to pull when I started working on it :).

**Comment by ubarni** [comment]
I would also love to have this feature to adjust the power usage to my solar power delivered.

**Comment by jmtatsch** [comment]
> I implemented the demand control on my fork

any particular reason why you implemented demand control instead of humidity instead of addition to it?

**Comment by lkaino** [comment]
> > I implemented the demand control on my fork
> 
> any particular reason why you implemented demand control instead of humidity instead of addition to it?

Humidity control was already present in HA climate entity. It was easy to implement, no other reasons.

**Comment by dOn-MoP** [comment]
the main reason for me to use this feature is to make the outside unit not having to run in intervals / switching on/off all the time when the heating demand is low. 
That behaviour (high on/off count) has a negative effect on the lifetime of the device.

**Comment by lkaino** [comment]
> I implemented the demand control on my fork: https://github.com/lkaino/daikin_residential/tree/demand_control_based_on_humidity
> 
> You control it by setting the humidity in Home Assistant.
> 
> It's based on v2.2.2 as I forgot to pull when I started working on it :).

I merged v2.3.1 to the branch, humidity controls demand control:
https://github.com/lkaino/daikin_residential/tree/demand_control_based_on_humidity

**Comment by jwillemsen** [comment]
Maybe this can be a select entity with the values off, auto, and then 0 to 100 in increments of 10

**Comment by Calleh12** [comment]
> Maybe this can be a select entity with the values off, auto, and then 0 to 100 in increments of 10

FYI, the app lets you do increments of 5.

**Comment by dOn-MoP** [comment]
...and minimum is 40 % :)

**Comment by jwillemsen** [comment]
Yes, below the meta data for fixed, will have a look at a select entity as part of my refactoring of https://github.com/speleolontra/daikin_residential_altherma

```
                "modes": {
                  "fixed": {
                    "stepValue": 5,
                    "value": 100,
                    "minValue": 40,
                    "maxValue": 100,
                    "settable": true
                  },
```

**Comment by jwillemsen** [comment]
Added support for reading back the `demandControl` setting to https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-climatecontrolrework

**Comment by jwillemsen** [comment]
See https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.2.0 for a new release with support for demandControl

**Comment by turbolooser** [comment]
How could I use this now with my Daikin non-Altherma AC unit?

**Comment by jwillemsen** [comment]
My forked version is for the Onecta app Daikin devices *including* the Altherma, regular Daikin AC Units are also supported now ;-).

**Comment by turbolooser** [comment]
> My forked version is for the Onecta app Daikin devices _including_ the Altherma, regular Daikin AC Units are also supported now ;-).

so which forked repo exactly? (trying to avoid any wrong direction here).
 this one: https://github.com/jwillemsen/daikin_residential_altherma ?
 if not could you please share the link?

**Comment by jwillemsen** [comment]
Yes, see https://github.com/jwillemsen/daikin_residential_altherma. My integration can exist besides this integration, so you can just add it and see how it works, you will see all AC units twice until you remove one of the two integrations.
