### ISSUE TITLE
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))

### ISSUE THREAD

**Issue by agamez** [rospogrigio/daikin_residential#72]
Hi,

I can't seem to login, this is the full error:

Logger: custom_components.daikin_residential.config_flow
Source: custom_components/daikin_residential/config_flow.py:58
Integration: Daikin Residential Controller ([documentation](https://github.com/rospogrigio/daikin_residential/), [issues](https://github.com/rospogrigio/daikin_residential/issues))
First occurred: 10:52:27 (1 occurrences)
Last logged: 10:52:27
Failed to retrieve Access Token: ('Error trying to extract API version: %s', SSLError(MaxRetryError("HTTPSConnectionPool(host='cdns.gigya.com', port=443): Max retries exceeded with url: /js/gigya.js?apiKey=3_xRB3jaQ62bVjqXU1omaEsPDVYC0Twi1zfq1zHPu_5HFT0zWkDvZJS97Yw1loJnTm (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))")))

It looks like there's some SSL problem, but the certificate of cdns.gigya.com seems OK to me. In the meantime, while this issue is investigated further, is there any way to bypass SSL verification, as I can check it by myself and see that it is okay to continue even if the software isn't able to?

**Comment by Brice187** [comment]
```
2022-10-02 07:45:16.669 ERROR (MainThread) [custom_components.daikin_residential.config_flow] Failed to retrieve Access Token: ('Error trying to follow redirect: %s', SSLError(MaxRetryError("HTTPSCo
nnectionPool(host='fidm.eu1.gigya.com', port=443): Max retries exceeded with url: /saml/v2.0/3_xRB3jaQ62bVjqXU1omaEsPDVYC0Twi1zfq1zHPu_5HFT0zWkDvZJS97Yw1loJnTm/idp/sso?SAMLRequest=fVJPb9owHL3vU0S%2B
O7FNIY1FUrEyVBCVOghs7QUZx6FuYzvEDrR8%2Bhko1Xrp0db7p%2Fd%2B%2FZs3VQU70VhpdApwiEAgNDeF1JsULPIRvAY32Y%2B%2BZaoiNR207lnPxLYV1gUDa0XjPO%2FWaNsq0cxFs5NcLGbTFDw7V1saRQWTr1LDVktembaAdWOKkHmZULRw72UgDpliB%2B
NNN1o6E3KjopNdJIu6Ebb26gIEQ4%2BVmrlTzot6KQvlhXC4kZt39kmNdiREUWf1NvvZeWG%2Fe2S9fNn%2BXWCj2C%2F7MFw%2B3qJ8L%2FGh3OLD3UO76t6NcnT48zrcPU3mSfy4x5WZ6FwdE0TWGhCMhylYMZwQlKw5ZGTdg1e9bgyZiBlE17iTJEUpyg73UGtb
MdbWMe1SQBAhECOISI5ietWluBd2E%2FIEguWldHIs3c%2BgLT3XnIK20dQwKy3VTAlLHafzwf2Ueij1DTrDTQWy8yr0ZNgEI9Mo5r7nHn9kAcsTlArtpHv%2F4v09nV0WB9kRdt6NfgxHbU0%2FN13Np%2BNkO6l53I%2F%2BT5l9PL%2BeUvYP&RelayState=H4
sIAAAAAAAAAD2RW5OiMBCF_0uejcPNEHxDRIXVGUdEVra2tkISJNyCKDjj1P73zb7M21d1zuk-1f0FCJgDPsAHv92h_ifaBs417KgNJiBTirf0FFFFdl-ZDtKMXGM3XFdaodloHEXZZsrAlIERUYl2aEUuOJu_vNTyIlqlcaVRybjCXGHk7rYKL2D-C8iOt4KB3xNQ
KGURbQqyjmzXLK4p9rD2qK4Hb-MWZz9meJHv15a1j-DnmJ7VAKESr3GCq5N3wcFsdXbb04feB8lQdTGujKrs1jLdrq7um1g1WCXK_9uNGVJYKUTV4rJ6HfT9aPA3s6bOqD36xR6j2uWBbOkD98j0P4I-effStQi5bx2yYcm5vV8u7umzjeIfPzuZlDAbntoTxjTsEn
8GIY993TcHxzpDbzgvt8wwV58JOyXithEba-2Fx2MRtlo5Nqf3IkDNMU53qD2gpbljLXY3h-OWaoMTlreROD7LpWpcf18YqhPTWg4Mdr1kUzLci-n3A6ekIU9VXl5acZdTKhuVbcBcR8hCDrJ1NAEdmOekvvEJ6NVQxzIzwh0KCSE5tEzdgBhnGswoNSzdwhnOLfD3
Hy7r9xcoAgAA.H4sIAAAAAAAAALtY7Ph2ToBe2l2RTXZ7XmnnTz_0k_kOX9CN3N6wGmF_X1kArOhLNyAAAAA.3 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: se
lf signed certificate (_ssl.c:997)')))")))
```

**Comment by Brice187** [comment]
my local dns blocker (pihole) blocked the access

**Comment by agamez** [comment]
Thanks @Brice187 , it was a similar case to yours. Make always sure that there isn't any adblocker active, or that it is properly configured to let connections to Daikin servers work!
