### ISSUE TITLE
Component Load Failure in HA 2022.7.0 B3

### ISSUE THREAD

**Issue by sembeeuk** [rospogrigio/daikin_residential#76]
Looks like there might be a problem with this component and the latest build of HA (in BETA at the time of writing). 

Version of HA: 2022.7.0b3

Logger: homeassistant.setup
Source: setup.py:162
First occurred: 10:56:30 AM (1 occurrences)
Last logged: 10:56:30 AM

Setup failed for custom integration daikin_residential: Unable to import component: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

I will continue to test the BETA builds as they are released to see if the issue is cleared from that side.

**Comment by emanuelst** [comment]
Hi, I think this is related to https://github.com/rospogrigio/daikin_residential/issues/63 and should be fixed by updating oic to 1.4.0, as in the newest commit https://github.com/rospogrigio/daikin_residential/commit/7e61c881b2da63cb173c001014ac55e2f8896db8 (not released yet as far as I know)

**Comment by user45876** [comment]
Just here to confirm that it is the same issue in the final version 2022.7.0, which is no surprise. Gladly waiting for a release.

**Comment by mgiebels** [comment]
Here same problem with 2022.07
Can’t restart homeassistant anymore because of the problem hope update released soon

**Comment by ju1ced** [comment]
> Hi, I think this is related to #63 and should be fixed by updating oic to 1.4.0, as in the newest commit [7e61c88](https://github.com/rospogrigio/daikin_residential/commit/7e61c881b2da63cb173c001014ac55e2f8896db8) (not released yet as far as I know)

did this change and it indeed works again, thanks for this.

**Comment by sembeeuk** [comment]
The version released earlier today appears to have resolved the issue with the release version of HA. Thanks for the prompt attention to the matter.

**Comment by mgiebels** [comment]
Problem Solved! thanks!
