### ISSUE TITLE
New HA version breaks daikin residential

### ISSUE THREAD

**Issue by XilefTech** [rospogrigio/daikin_residential#77]
Since the newest HomeAssistant update, this integration is broken. 

On load it errors with the message:
`Setup failed for custom integration daikin_residential: Unable to import component: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)`

to make this integration useful again, a fix for this would be actually quite useful
thx

**Comment by jwillemsen** [comment]
See #76

**Comment by rospogrigio** [comment]
You must update the component. The issue is fixed.
