### ISSUE TITLE
Unable to import component: No module named 'custom_components.daikin_residential.2'

### ISSUE THREAD

**Issue by marc4s** [rospogrigio/daikin_residential#81]
ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration daikin_residential: Unable to import component: No module named 'custom_components.daikin_residential.2'

this string or parts of it like "residential.2" cannot be found in the config/custom directory.

any idea?
problem exist since ~ 2weeks - I think since update homassistant to 2022.07

thanks
Marc

**Comment by marc4s** [comment]
PS: I started ~ 1 year ago with 2.0.x - never had to update, never had any issues...
I did an upgrade with git pull:
daikin_residential/manifest.json:4:  "version": "2.2.1"

but no changes. still the same...

**Comment by rospogrigio** [comment]
Don't know mate, maybe try to install it via HACS instead of manually and see if it solves. I'm on 2022.07.6 and it still works flawlessly.
Bye

**Comment by marc4s** [comment]
I installed HACS but it is NOT listing daikin / residential - ?? Anything to add for?



Integrations Version: | 1.26.2 -- | --
Frontend Version: | 20220714083628
Repositories: | 1072
Heruntergeladene Repositories: | 1




Version | core-2022.7.6
-- | --
Installationstyp | Home Assistant Core
Entwicklung | false
Supervisor | false
Docker | false
Benutzer | homeassistant
Virtuelle Umgebung | true
Python-Version | 3.9.13
Betriebssystemfamilie | Linux
Betriebssystem-Version | 5.4.0-1065-raspi
CPU-Architektur | aarch64
Zeitzone | Europe/Berlin

**Comment by rospogrigio** [comment]
You must add my repo as a custom repository. Go to HACS -> 3 dots on the top right -> Custom repositories -> enter my URL and select Integration as Category, then you should find it when you add a new integration.

**Comment by marc4s** [comment]
Thanks!
and funny. Now it is working - with the SAME config as before (.storage/core.config_entries) was accepted and eversthing is fine as before.
