### ISSUE TITLE
Invalid repository?

### ISSUE THREAD

**Issue by bjornvaessen** [rospogrigio/daikin_residential#86]
Trying to add this repository, HA throws the error:

https://github.com/rospogrigio/daikin_residential is not a valid add-on repository

Running HA 2022.9.1

**Comment by Roelvm12** [comment]
> Trying to add this repository, HA throws the error:
> 
> https://github.com/rospogrigio/daikin_residential is not a valid add-on repository
> 
> Running HA 2022.9.1

How did you fix this?

**Comment by bjornvaessen** [comment]
> > Trying to add this repository, HA throws the error:
> 
> > 
> 
> > https://github.com/rospogrigio/daikin_residential is not a valid add-on repository
> 
> > 
> 
> > Running HA 2022.9.1
> 
> 
> 
> How did you fix this?

A full RPi reboot fixed it 🙂

**Comment by gaardiolor** [comment]
Got the error when I went to hacs > add-ons > add-on store > 3 dots at top right > repositories 

Had more success by going to hacs > integrations > 3 dots at top right > custom repositories. Add it there.
