### ISSUE TITLE
Humidity entity

### ISSUE THREAD

**Issue by domerich** [rospogrigio/daikin_residential#88]
Hi Guys, I am a noob but would it be possible to read out the room humidity sensor?

**Comment by jwillemsen** [comment]
I don't have humidity exported by my daikin devices, please go to the integration settings and download the diagnostics and attach it here (please first remove the token/passwords/etc). We have to know where this data is exactly exported by daikin

**Comment by domerich** [comment]
I hope I got the right one
[config_entry-daikin_residential-8f5a9fa31f94444b820bf7ecd84a07ce.json.txt](https://github.com/rospogrigio/daikin_residential/files/9593771/config_entry-daikin_residential-8f5a9fa31f94444b820bf7ecd84a07ce.json.txt)

**Comment by domerich** [comment]
> I hope I got the right one [config_entry-daikin_residential-8f5a9fa31f94444b820bf7ecd84a07ce.json.txt](https://github.com/rospogrigio/daikin_residential/files/9593771/config_entry-daikin_residential-8f5a9fa31f94444b820bf7ecd84a07ce.json.txt)
> 
> ```
>             },
>             "roomHumidity": {
>               "settable": false,
>               "value": 50,
>               "stepValue": 1,
>               "minValue": 25,
>               "maxValue": 85
>             },
> ```

I hope I got the right one
[config_entry-daikin_residential-8f5a9fa31f94444b820bf7ecd84a07ce.json.txt](https://github.com/rospogrigio/daikin_residential/files/9593771/config_entry-daikin_residential-8f5a9fa31f94444b820bf7ecd84a07ce.json.txt)

            },
            "roomHumidity": {
              "settable": false,
              "value": 50,
              "stepValue": 1,
              "minValue": 25,
              "maxValue": 85
            },

**Comment by jwillemsen** [comment]
Yes, that is the correct one, seems this has to be implemented, `outside_temperature` could be used as starting point, mostly a copy/paste effort

**Comment by droscy** [comment]
@domerich could you please test PR #101?

**Comment by domerich** [comment]
> @domerich could you please test PR #101?

how can I download the 3 files? I don't understand

**Comment by droscy** [comment]
I think this issue can be closed.
