### ISSUE TITLE
Missing entities for FTXM20R5V1B ?

### ISSUE THREAD

**Issue by alexthevenot** [rospogrigio/daikin_residential#9]
Hello rospogrigio,

First of all, thank you for your great work, I recently bought a FTXM20R5V1B unit from Daikin and directly started to try to connect it to hass but it was not straight forward. And thanks to your integration, I was finally able to connect it, so thank you.

I am not sure if it's an issue or just "normal" but in hass, I have 10 entities for my integration :
![image](https://user-images.githubusercontent.com/5883214/129386745-83004d52-fe4b-4749-a7d6-12a7a5a38611.png)
But I don't see any switch to turn the unit on and off for example.
Maybe it's just not implemented in your integration ?

If I can be any help..
Thank you,
Alexandre

**Comment by alexthevenot** [comment]
Ok forget it.. I should have looked at climate integration before talking.... -_-

Thank you anyway for your work !

**Comment by rospogrigio** [comment]
No problem man, bye!
