### ISSUE TITLE
Fan Mode not working

### ISSUE THREAD

**Issue by Nexpola** [rospogrigio/daikin_residential#93]
Hi, i'm using Home Assistant 2022.10 and latest version of this integration to control two Daikin Perfera.
The Fan Mode menu is working correctly when selecting "Auto" or "Silence" only. Speed values from 1 to 5 are not working instead.
Thank you.

**Comment by mountaindude** [comment]
I see this too.
Haven't dig into it yet, first thought was that something changed with
Daikin's cloud service, but maybe it's related to the new HA version.

**Comment by Nexpola** [comment]
I've just reinstalled an old 2022.6 where I'm sure Fan Mode was working, but nothing. Fan speed (from 1 to 5) doesn't work.
I suppose something on the Daikin's cloud service has been changed.

**Comment by Dan1elGe** [comment]
For me that seems to be a problem with Daikin cloud.

Since several days both the Onecta App from Daikin and the HA integration have massive problems with updating the actual state of the airon devices. After 10-20s the status is always reset to off although the command has been sent and processed.

**Comment by andreas-amlabs** [comment]
Same issue here, Onecta app also broken.
Also I get this in my HA logs, 
https://github.com/rospogrigio/daikin_residential/pull/74

**Comment by Nexpola** [comment]
Maybe we are talking about the same issue.
Onecta app is working correctly in my case (Android app version: 3.8.0-14945)

**Comment by rospogrigio** [comment]
Hi all, this is happening on my appliance too. It has to be something changed on their cloud calls because it is failing also when using python scripts (so, outside HA), which means it is not related to the HA version.
I'll see if I can understand the reason and provide a fix.
PR #74 does not solve the issue (on my setup, at least).
Bye

**Comment by Dan1elGe** [comment]
In my case a DNS filter (adguard) blocked the access to kinesis.eu-west-1.amazonaws.com which seems to be the host of Daikin Cloud for Germany. I added an exception to the adguard installation and now both Onecta App and HA Integration work again.

**Comment by intrinseca** [comment]
> In my case a DNS filter (adguard) blocked the access to kinesis.eu-west-1.amazonaws.com which seems to be the host of Daikin Cloud for Germany. I added an exception to the adguard installation and now both Onecta App and HA Integration work again.

Having seen the issues Pi-Hole users were having, I don't know why it didn't occur to me to check this! Fixed this issue for me too.

**Comment by rospogrigio** [comment]
Well this is weird because I'm not using Pi-Hole but still experience this issue. And why should only this command fail? Why not any of the others? I really wonder what's going on here ...

**Comment by intrinseca** [comment]
I was seeing the complete failure to update status in HA and Onecta, rather than anything specific to fan mode (maybe I got my issues confused!). 

And I should be clear, I use AdGuard, not Pi-Hole. Similar but different!

**Comment by rospogrigio** [comment]
But AdGuard installed where? On the RPi? Or on your phone?

**Comment by intrinseca** [comment]
Network-wide, I use a local AdGuard server as my DNS for the network, so it would have blocked Onecta on my phone on WiFi as well as HA.

**Comment by intrinseca** [comment]
Not that I think it matters, but on another Raspberry Pi. My setup is probably over-complicated!

**Comment by intrinseca** [comment]
> In my case a DNS filter (adguard) blocked the access to kinesis.eu-west-1.amazonaws.com which seems to be the host of Daikin Cloud for Germany. I added an exception to the adguard installation and now both Onecta App and HA Integration work again.

I have raised an issue against Adguard: https://github.com/AdguardTeam/AdguardFilters/issues/131918

**Comment by intrinseca** [comment]
I run AdGuard home as a docker container.

https://hub.docker.com/r/adguard/adguardhome

My Pi's all run docker directly, I don't use HassOS. AdGuard happens to run on a different Pi to Home Assistant, but it doesn't have to.

**Comment by rospogrigio** [comment]
Cool. I use HA on docker too... I'll give it a try, thank you!

**Comment by mountaindude** [comment]
I have tested the ad-blocker hypothesis here, no luck for me.
For various reasons Pi-Hole has been disabled for several weeks now (well before the Daikin issue started), so it's not causing the issue for me. 

Might have been just a coincidence, but I was thrown out of the Onecta app the other day, having to log back in.
I hoped it had to do with Daikin fixing something on their end, but things were still the same once I got back into the app.

**Comment by BlazDT** [comment]
AdGuard filter update available in a few hours for DNS filters. Our DNS servers will take a bit longer to synchronize.

**Comment by andreas-amlabs** [comment]
Pi-Hole user here, to get the plugin to work I whitelisted like
(\.|^)eu1\.gigya\.com$

This was done prior to these issues and disabling the pi-hole does NOT resolve This issue
Only blocked item I can see, reg. this app, is app-measurement.com

At least 4 days now, and no update on the Onecta app - which I find strange, since that is also not working

**Comment by TRIROG** [comment]
Onecta app has the same issue. Fan speed setting is hit or miss… most of the time miss…

**Comment by andreas-amlabs** [comment]
Noticed that iPhone app has version Version 3.9.3 released Oct. 17, android has yet to receive this release.
Has anyone tested the Onecta iPhone 3.9.3 app ? (I only have android)

**Comment by andreas-amlabs** [comment]
Yeah, so some progress :)

During my contact with Daikin support, I decided to give the iPhone Onecta app a go
Download, install, login (same account as android)

Tada ... it works

Magic, back to android ... which NOW also works !
back to Home assistant ... which NOW also works ! (so this plugin)

However #74 is still an issue, cannot really set (and keep) 1-5 without it

I do not know what unlocked the issue

**Comment by rospogrigio** [comment]
I think they fixed it cloud-side, now it is somewhat working for me too.
#74 does not fix this however, I just made PR #100 that does. The only thing is that it updates the speed immediately when changing from one 1-5 number to another, but it needs some 30 seconds to update when passing from Silence/Auto to 1-5 values. I think I need to set the "fixed" mode before setting the 1-5 value, will try something tomorrow if I can find the time. 
In the meantime you can check whether the PR is working.
Bye
