### ISSUE TITLE
Controls not working for models BRP069B4x

### ISSUE THREAD

**Issue by gasparhugoricardo** [rospogrigio/daikin_residential#94]
Since the last HA Update, the controls for the units with the BRP069B4x adapter model stopped working.
We can still see the Sensor values, but the controls are unavailable. I have other units in my home with the model BRP069C4x and they're working correctly.

I can see this error in the logs:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/daikin_residential/daikin_base.py:116
Integration: Daikin Residential Controller (documentation, issues)
First occurred: October 12, 2022 at 9:44:26 AM (3367 occurrences)
Last logged: 5:50:37 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 812, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 338, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
  File "/config/custom_components/daikin_residential/climate.py", line 254, in preset_mode
    if self._device.preset_mode_status(mode) == ATTR_STATE_ON:
  File "/config/custom_components/daikin_residential/daikin_base.py", line 170, in preset_mode_status
    return self.getValue(mode)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 116, in getValue
    return data["value"]
KeyError: 'value'

<img width="1031" alt="Screenshot 2022-10-14 at 17 49 02" src="https://user-images.githubusercontent.com/8532920/195901128-8879f688-6f8a-4edb-9a16-64f4778e612f.png">
<img width="994" alt="Screenshot 2022-10-14 at 17 51 30" src="https://user-images.githubusercontent.com/8532920/195901129-b7316c7b-0ef6-48a9-8e82-59fc005080cb.png">

**Comment by VederJay** [comment]
Seeing the same thing on my installation.

**Comment by rospogrigio** [comment]
I'm order to debug this, you'd need to post your diagnostic files (the Integration's or the device's ones, or both would be better) so we can understand which Value is missing.

**Comment by VederJay** [comment]
Integration:
[config_entry-daikin_residential-200e3025d9977bb710c9a316e64577cb.json.txt](https://github.com/rospogrigio/daikin_residential/files/9794983/config_entry-daikin_residential-200e3025d9977bb710c9a316e64577cb.json.txt)

One of the devices:
[daikin_residential-200e3025d9977bb710c9a316e64577cb-Bureau Jeroen-d775887acd4c92ac113f21c9f04f85aa.json.txt](https://github.com/rospogrigio/daikin_residential/files/9794992/daikin_residential-200e3025d9977bb710c9a316e64577cb-Bureau.Jeroen-d775887acd4c92ac113f21c9f04f85aa.json.txt)

**Comment by rospogrigio** [comment]
OK, I had a look and looks like BRP069B4x devices lack (or stopped supporting) holidayMode, since you get this in your json:
`          "holidayMode": {
            "error": "INVALID_CHARACTERISTIC",
            "ref": "#holidayMode",
            "settable": true,
            "value": {
              "enabled": false,
              "startDate": "2022-03-27T22:00:00Z",
              "endDate": "2022-04-04T21:59:59Z",
              "desiredIsHolidayModeActive": null
            }`
Can you check if PR #96 fixes your issue? I believe you won't be able to use that preset, I don't know if it's available in the Onecta app.
Let me know...

**Comment by gasparhugoricardo** [comment]
Hi @rospogrigio,
I left a comment on the PR.
I've tested the fix and it's working properly with both versions of the device. Thanks for your great work!
